### PR TITLE
Extend XHR to handle API auth issues.

### LINKED ISSUE #48: handle expired tokens and forbidden api calls by default
```javascript
const xhr = window.XMLHttpRequest
const nativeOpen = xhr.prototype.open

xhr.prototype.open = function () {
  this.addEventListener('load', function () {
    if (this.responseURL.indexOf(API_URL) === -1) return
    switch (this.status) {
      case 401:
        const err = this.responseText
        logout()
        showNotification({error: parseErrorDetail(err)})
        break

      case 402:
        Rollbar.error('User subscription is no longer valid! @TODO: this need to be handled.')
        break

      case 403:
        logout()
        break
    }
  })
  nativeOpen.apply(this, arguments)
}
```

### PR DESCRIPTION
**Pull request by staydecent**
Closes #48

By default, doesn't do much, but lays the groundwork for the project. Let me know if you think there should be more of a default handler for these 40x responses.

### CODE REVIEW

**Comment by weslord** [comment]
Would be a little clearer if `extensions.js` was something like `xhr-extensions.js`

**Comment by staydecent** [comment]
Yeah for sure. My thinking is it could be a nice spot for other extensions, or setting of globals. 🤔

**Comment by weslord** [comment]
`/src/extensions/xhr.js` ?

**Comment by staydecent** [comment]
Probably no need to pre-optimize. Renamed the file.

File: src/util/extend-xhr.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+// You may wish to show a notification, redirect to a new page, or reload all state.
+const logout = () => {
+  window.localStorage.removeItem('token')
+  // window.location.reload()
+}
+
+xhr.prototype.open = function () {
+  this.addEventListener('load', function () {
+    if (this.responseURL.indexOf(API_URL) === -1) return
```
Comment (weslord) [inline src/util/extend-xhr.js]: If I ran into a situation where this was short-circuiting, I'd greatly appreciate a warning or error in the console so I could figure out why my requests weren't doing anything.

Comment (staydecent) [reply src/util/extend-xhr.js]: Oh haha.. Yeah it should not be returning before calling the nativeOpen 🥀

Comment (staydecent) [reply src/util/extend-xhr.js]: @weslord I'm not sure I understand how this could short-circuit? This is _adding_ an event listener to the load event of the individual xhr instance. It is not replacing the native load handler. So, if the xhr is *not* getting a response from our API_URL then it does nothing extra.

The native xhr `open` handler is still called.

Comment (weslord) [reply src/util/extend-xhr.js]: Right you are! Whoops.
